# Workflow's name
name: linux-gcc

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup premake
        uses: abel0b/setup-premake@v1
      - name: Build
        run: |
          premake5 gmake
          make -j2 config=release
      - name: Test
        run: chmod +x moon && ./moon test/main_test.lua
        if: startsWith(github.ref, 'refs/tags/')
      - name: Publish
        run: |
          mkdir publish
          cp -r lualib publish/
          cp -r service publish/
          cp -r example publish/
          cp moon publish/
          cd publish
          tar -zcvf linux-amd64.tar.gz ./*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
