# Workflow's name
name: release

# Workflow's trigger
on:
  push:
    tags:
      - "v*.*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup premake
        uses: abel0b/setup-premake@v1
      - name: Build
        run: |
          premake5 gmake
          make -j2 config=release
      - name: Test
        run: chmod +x moon && ./moon example/main.lua 1
      - name: Publish
        run: |
          mkdir publish
          cp -r lualib publish/
          cp -r service publish/
          cp -r example publish/
          cp moon publish/
          cd publish
          tar -zcvf linux-amd64.tar.gz ./*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup premake
        uses: abel0b/setup-premake@v1
      - name: Build
        run: |
          premake5 gmake --cc=clang
          make -j2 config=release
      - name: Test
        run: chmod +x moon && ./moon example/main.lua 1
      - name: Publish
        run: |
          mkdir publish
          cp -r lualib publish/
          cp -r service publish/
          cp -r example publish/
          cp moon publish/
          cd publish
          tar -zcvf darwin-amd64.tar.gz ./*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/darwin-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup premake
        uses: abel0b/setup-premake@v1
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Build
        run: |
          premake5.exe vs2019
          msbuild /m Server.sln /p:configuration="release"
      - name: Test
        run: .\moon.exe example/main.lua 1
      - name: Publish
        shell: bash
        run: |
          mkdir publish
          cp -r lualib publish/
          cp -r service publish/
          cp -r example publish/
          cp moon.exe publish/
          cd publish
          tar -zcvf windows-amd64.tar.gz ./*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/windows-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
