
# Workflow's name
name: windows-vs2019

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  windows-vs2019:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup premake
        uses: abel0b/setup-premake@v1
      - name: configure
        run: premake5.exe vs2019
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: build
        run: msbuild /m Server.sln /p:configuration="release"
      - name: test
        run: .\moon.exe test/main_test.lua

